version: '3.8'

services:
  web:
    build: .
    image: octoprobe-testbed_micropython-fastapi:${IMAGE_VERSION}
    command: uvicorn app.main:app --host 0.0.0.0 --port 443 --ssl-keyfile=${SSL_KEY} --ssl-certfile=${SSL_CERT}
    volumes:
      - ./.:/server
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - '${APP_HOST}:${APP_PORT}:443'
    user: '${UID}:${GID}'
    env_file:
      - .env
