version: '3.8'

services:
  web:
    build: .
    image: octoprobe-testbed_micropython-fastapi:${IMAGE_VERSION}
    command: uvicorn server.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/server
    ports:
      - 8000:8000
    
    env_file:
      - .env
