version: '3.8'

services:
  web:
    build: .
    image: octoprobe-testbed_micropython-fastapi:${IMAGE_VERSION}
    entrypoint: ["/bin/sh", "-c", "app/start_uvicorn.sh"]
    volumes:
      - ./.:/server
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - '${APP_HOST}:${APP_PORT}:443'
    user: '${UID}:${GID}'
    env_file:
      - .env
